services:
    mongo1:
        image: mongo:latest
        container_name: mongo1
        ports:
            - "27018:27017"
        command: ["--replSet", "rs0", "--bind_ip_all"]
        volumes:
            - mongo1-data:/data/db
        networks:
            - master
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        
    mongo-setup:
        image: mongo:latest
        container_name: mongo-setup
        depends_on: [mongo1]
        volumes:
            - ./init-mongo-replicaset.sh:/scripts/init-mongo-replicaset.sh
        entrypoint: ["bash", "/scripts/init-mongo-replicaset.sh"]
        networks:
            - master
        restart: "no"

    broker:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        networks:
            - master
    
    global-acquirer:
        container_name: global-acquirer
        image: node:20
        ports:
            - 3000:3000
        volumes:
        - ./global-acquirer:/backend
        command: bash -c "cd backend && npm i && npm start"
        restart: on-failure
        depends_on:
            broker:
                condition: service_healthy
        networks:
            - master

    simur:
        image: simur-backend:1.0.0
        container_name: simur
        ports:
            - "7033:7033"
            - "5254:5254"
        env_file:
            - ./simur-backend/.env
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://0.0.0.0:7033;http://0.0.0.0:5254
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
        volumes:
            - ~/.aspnet/https:/https:ro
        depends_on:
            broker:
                condition: service_healthy
            mongo1:
                condition: service_healthy
        networks:
            - master

volumes:
    rabbitmq_data:
    mongo1-data:
        driver: local

networks:
    master:
        driver: bridge